name : Tests coverage

on : 
  push : 
    branches : 
      - main
  pull_request :
    branches :
      - main

jobs :
  build_back:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back #se mettre dans le dossier back de github pour exécuter
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml #clean avant l'install des packages
    - name: Run backend tests with coverage
      run: mvn jacoco:report # Génère le rapport de couverture avec JaCoCo

    - name: Upload backend coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: back_coverage
        path: target/back_coverage/jacoco/ # Chemin vers les fichiers de couverture JaCoCo

      
