name : Tests coverage

on : 
  push : 
    branches : 
      - main
  pull_request :
    branches :
      - main

jobs :
  build_back:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back #se mettre dans le dossier back de github pour exécuter
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml #clean avant l'install des packages
    - name: Add and commit coverage
      run: git pull
           mv target/site back_coverage 
           git add .
           git commit -m "Tests backend coverage report"
           git push origin main

      
